### ISSUE TITLE
WOTLK Classic Capping is not showing timers

### ISSUE THREAD

**Issue by vestrene** [BigWigsMods/Capping#114] opened 2022-09-01 14:16 UTC
## Describe the problem
When doing Alterac Valley, most timers for capping are not showing up

### What steps will reproduce the problem?

1.  Log into WOTLK Classic
2.  Join AV
3.  See that timers are missing when people cap bunkers/towers

### What version of the addon are you using? (Stating 'latest' is not useful)
v1-bcc

### Do you have an error log of what happened?
No Lua error is fired, the addon simply doesn't pick up all events (Typically graveyards are picked up, bunkers and towers are not).

**Comment by icemansparks** [comment] 2022-09-02 13:54
i can confirm the change above seems to be working, however, the mines still seem to be bugged.

**Comment by ssateneth** [comment] 2022-09-02 14:44
also wanted to add, the 300 second timer seems to be too long. towers/bunkers and gy's cap after 245 seconds.

**Comment by funkydude** [comment] 2022-09-02 17:32
> also wanted to add, the 300 second timer seems to be too long. towers/bunkers and gy's cap after 245 seconds.

That's what it's already set to. Not sure where you're getting 300 from, that's original classic.

**Comment by funkydude** [comment] 2022-09-02 18:12
Thanks for all the reports! Will be fixed in the next release (very soon)

**Closed** 2022-09-02 18:11 UTC
Labels: wotlkc
