### ISSUE TITLE
Feature Request: AB Time remaining estimate?

### ISSUE THREAD

**Issue by Havenloft** [BigWigsMods/Capping#71] opened 2020-03-21 00:31 UTC
This is the one thing that DBM - PvP Mod does better than Capping. I would love to see this feature implemented in Capping as I would no longer have any need for DBM - PvP Mod.

**Comment by audiosmith** [comment] 2020-03-27 03:05
+1 requesting this feature implemented for Classic WoW

**Comment by funkydude** [comment] 2021-06-01 22:31
Duplicate of #70

**Closed by funkydude** 2021-06-01 22:31 UTC
